p8105_hw1_waa2119
================
William Anderson
2022-09-20

``` r
library(tidyverse)
```

\#P8105 HW 1 Assignment

This loads the penguins data set

``` r
data("penguins", package = "palmerpenguins")

head(penguins, 20)
```

    ## # A tibble: 20 × 8
    ##    species island    bill_length_mm bill_depth_mm flipper_…¹ body_…² sex    year
    ##    <fct>   <fct>              <dbl>         <dbl>      <int>   <int> <fct> <int>
    ##  1 Adelie  Torgersen           39.1          18.7        181    3750 male   2007
    ##  2 Adelie  Torgersen           39.5          17.4        186    3800 fema…  2007
    ##  3 Adelie  Torgersen           40.3          18          195    3250 fema…  2007
    ##  4 Adelie  Torgersen           NA            NA           NA      NA <NA>   2007
    ##  5 Adelie  Torgersen           36.7          19.3        193    3450 fema…  2007
    ##  6 Adelie  Torgersen           39.3          20.6        190    3650 male   2007
    ##  7 Adelie  Torgersen           38.9          17.8        181    3625 fema…  2007
    ##  8 Adelie  Torgersen           39.2          19.6        195    4675 male   2007
    ##  9 Adelie  Torgersen           34.1          18.1        193    3475 <NA>   2007
    ## 10 Adelie  Torgersen           42            20.2        190    4250 <NA>   2007
    ## 11 Adelie  Torgersen           37.8          17.1        186    3300 <NA>   2007
    ## 12 Adelie  Torgersen           37.8          17.3        180    3700 <NA>   2007
    ## 13 Adelie  Torgersen           41.1          17.6        182    3200 fema…  2007
    ## 14 Adelie  Torgersen           38.6          21.2        191    3800 male   2007
    ## 15 Adelie  Torgersen           34.6          21.1        198    4400 male   2007
    ## 16 Adelie  Torgersen           36.6          17.8        185    3700 fema…  2007
    ## 17 Adelie  Torgersen           38.7          19          195    3450 fema…  2007
    ## 18 Adelie  Torgersen           42.5          20.7        197    4500 male   2007
    ## 19 Adelie  Torgersen           34.4          18.4        184    3325 fema…  2007
    ## 20 Adelie  Torgersen           46            21.5        194    4200 male   2007
    ## # … with abbreviated variable names ¹​flipper_length_mm, ²​body_mass_g

# Problem 1

-   The penguins data set contains the following information in each
    column: species, island, bill_length_mm, bill_depth_mm,
    flipper_length_mm, body_mass_g, sex, year

-   The penguin species ranges from Adelie, Gentoo, and Chinstrap.

-   The islands these penguins reside on is Torgersen, Biscoe and Dream.

-   The sex of these penguins are both male and

female.

-   The year this data was collected ranges between 2007

2008, and 2009.

-   The mean, median, and standard deviation of the bill length of these

penguins is 43.9219298,

44.45,

and 5.4595837 mm respectively.

-   The mean, median, and standard deviation of the bill depth of these

penguins is 17.1511696,

17.3,

and 1.9747932 mm

respectively.

-   The mean, median, and standard deviation of the flipper length of

these penguins is 200.9152047,

197,

and 14.0617137 mm respectively.

Lastly, the the mean, median, and standard deviation of the body mass

of these penguins is 4201.754386,

4050, and

801.9545357 g respectively.

-   The size of the penguins data set is 344 rows by 8 columns

-   The mean flipper length of all penguins in the data set is
    200.9152047 mm

Now we will make a scatter plot of flipper length vs bill length

``` r
ggplot(penguins, aes(x = bill_length_mm, y = flipper_length_mm, color = species)) + geom_point()
```

    ## Warning: Removed 2 rows containing missing values (geom_point).

![](p8105_hw1_waa2119_files/figure-gfm/scatter%20plot%20of%20flipper%20length%20vs%20bill%20length-1.png)<!-- -->

``` r
ggsave("scatter_plot_HW1.pdf")
```

    ## Saving 7 x 5 in image

    ## Warning: Removed 2 rows containing missing values (geom_point).

# Problem 2

Now creating a tibble with various vectors inside

``` r
my_data_frame = tibble(
  
  my_random_sample = rnorm(n = 10, mean = 0, sd = 1),
  
  log_vec = my_random_sample > 0,
  
  char_vec = c("a", "b", "c", "d", "e", "f", "g", "h", "i", "j"),
  
  fact_vec = factor(c("First", "Second", "Third", "First", "Second", "Third", "First", "Second", "Third", "First"))
  
)
```

Now attempting to take the mean of the vectors within the tibble

``` r
avg_rand_samp = mean(pull(my_data_frame, my_random_sample))

avg_log_vec = mean(pull(my_data_frame, log_vec))

avg_char_vec = mean(pull(my_data_frame, char_vec))
```

    ## Warning in mean.default(pull(my_data_frame, char_vec)): argument is not numeric
    ## or logical: returning NA

``` r
avg_fact_vec = mean(pull(my_data_frame, fact_vec))
```

    ## Warning in mean.default(pull(my_data_frame, fact_vec)): argument is not numeric
    ## or logical: returning NA

We see that the mean of the random sample is -0.0861183, but we are
unable to calculate the mean of the logical: 0.5, mean of character: NA,
and mean of factor vector: NA as they are not numerical values

We can then convert their values to the numerical type

``` r
num_log_vec = as.numeric(pull(my_data_frame, log_vec))

num_char_vec = as.numeric(pull(my_data_frame, char_vec))

num_fact_vec = as.numeric(pull(my_data_frame, fact_vec))
```
